import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// TODO: replace with the actual questionSetId for "English Wizard - Lecture 09: Gender"
const questionSetId = 'cmtltiqdc002oah01xhjegg4h';

async function main() {
  await prisma.question.createMany({
    data: [
      // ━━━━━━━━━━━━━━━ Gender (English Wizard - Lecture 09) ━━━━━━━━━━━━━━━

      {
        questionSetId,
        slug: 'gender-feminine-poet',
        questionText: "What is the feminine gender of 'poet'?",
        optionA: 'Poetress',
        optionB: 'Poetess',
        optionC: 'Female poet',
        optionD: 'Poet',
        correctAnswer: 'B',
        explanation: "'Poet' takes 'ess' to form its feminine — poetess.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 1,
      },

      {
        questionSetId,
        slug: 'gender-masculine-duchess',
        questionText: "What is the masculine form of 'duchess'?",
        optionA: 'Earl',
        optionB: 'Dramatist',
        optionC: 'Dutchman',
        optionD: 'Duke',
        correctAnswer: 'D',
        explanation: "'Duchess' is the feminine of 'duke'.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 2,
      },

      {
        questionSetId,
        slug: 'gender-feminine-heir',
        questionText: "What is the feminine gender of 'heir'?",
        optionA: 'heiress',
        optionB: 'heires',
        optionC: 'haires',
        optionD: 'heirs',
        correctAnswer: 'A',
        explanation: "'Heir' forms its feminine by adding 'ess' — heiress.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 3,
      },

      {
        questionSetId,
        slug: 'gender-feminine-tiger',
        questionText: "What is the feminine gender of 'tiger'?",
        optionA: 'tigress',
        optionB: 'tigeress',
        optionC: 'tigerine',
        optionD: 'tigrina',
        correctAnswer: 'A',
        explanation: "The final vowel of 'tiger' is dropped before adding 'ess' — tigress.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 4,
      },

      {
        questionSetId,
        slug: 'gender-feminine-hero',
        questionText: "What is the feminine gender of 'hero'?",
        optionA: 'heroess',
        optionB: 'heroine',
        optionC: 'heros',
        optionD: 'herose',
        correctAnswer: 'B',
        explanation:
          "Foreign-origin masculines like 'hero' take 'ine' to form the feminine — heroine.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 5,
      },

      {
        questionSetId,
        slug: 'gender-opposite-wizard',
        questionText: "Give the opposite gender of 'wizard'.",
        optionA: 'witch',
        optionB: 'wizardess',
        optionC: 'female wizard',
        optionD: 'wizardine',
        correctAnswer: 'A',
        explanation: "'Wizard' and 'witch' form a completely different-word gender pair.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 6,
      },

      {
        questionSetId,
        slug: 'gender-feminine-drake',
        questionText: "What is the feminine gender of 'drake'?",
        optionA: 'drakess',
        optionB: 'hen',
        optionC: 'duck',
        optionD: 'drakenne',
        correctAnswer: 'C',
        explanation: "'Drake' (male duck) has 'duck' as its feminine form.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 7,
      },

      {
        questionSetId,
        slug: 'gender-masculine-bee',
        questionText: "What is the masculine form of 'bee'?",
        optionA: 'stag',
        optionB: 'colt',
        optionC: 'hart',
        optionD: 'drone',
        correctAnswer: 'D',
        explanation: "'Bee' is the feminine of 'drone'.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 8,
      },

      {
        questionSetId,
        slug: 'gender-identify-feminine-buck-sow',
        questionText: 'Identify the feminine gender —',
        optionA: 'buck',
        optionB: 'sow',
        optionC: 'hunter',
        optionD: 'baron',
        correctAnswer: 'B',
        explanation: "'Sow' is the feminine of 'boar'; the other options are masculine.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 9,
      },

      {
        questionSetId,
        slug: 'gender-select-feminine-nun',
        questionText: 'Select the feminine gender —',
        optionA: 'nun',
        optionB: 'bishop',
        optionC: 'clergy',
        optionD: 'hare',
        correctAnswer: 'A',
        explanation: "'Nun' is the feminine of 'monk' or 'friar'.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 10,
      },

      {
        questionSetId,
        slug: 'gender-female-horse',
        questionText: 'The female of a horse is called —',
        optionA: 'a stallion',
        optionB: 'a doe',
        optionC: 'a buck',
        optionD: 'a mare',
        correctAnswer: 'D',
        explanation: "A stallion's feminine counterpart is 'mare'.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 11,
      },

      {
        questionSetId,
        slug: 'gender-feminine-drone',
        questionText: "The feminine gender of 'drone' is —",
        optionA: 'bee',
        optionB: 'hind',
        optionC: 'ewe',
        optionD: 'lass',
        correctAnswer: 'A',
        explanation: "A completely different word, 'bee', is used as the feminine of 'drone'.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 12,
      },

      {
        questionSetId,
        slug: 'gender-feminine-ram',
        questionText: "The feminine of 'Ram' is —",
        optionA: 'ewe',
        optionB: 'hind',
        optionC: 'mare',
        optionD: 'sow',
        correctAnswer: 'A',
        explanation: "'Ram' (male sheep) has 'ewe' as its feminine form.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 13,
      },

      {
        questionSetId,
        slug: 'gender-masculine-bride',
        questionText: "The masculine gender of 'bride' is —",
        optionA: 'bridegroom',
        optionB: 'husband',
        optionC: 'brider',
        optionD: 'briden',
        correctAnswer: 'A',
        explanation: "'Bride' pairs with 'bridegroom' as its masculine form.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 14,
      },

      {
        questionSetId,
        slug: 'gender-feminine-fox',
        questionText: 'What is the feminine gender of fox?',
        optionA: 'foxen',
        optionB: 'vixen',
        optionC: 'female fox',
        optionD: 'none of the above',
        correctAnswer: 'B',
        explanation: "'Fox' uses a distinct word, 'vixen', for its feminine.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 15,
      },

      {
        questionSetId,
        slug: 'gender-feminine-swain',
        questionText: "What is the feminine gender of 'swain'?",
        optionA: 'swainess',
        optionB: 'witch',
        optionC: 'nymph',
        optionD: 'bitch',
        correctAnswer: 'C',
        explanation: "'Swain' (a rustic lover/young man) has 'nymph' as its feminine.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 16,
      },

      {
        questionSetId,
        slug: 'gender-opposite-roe',
        questionText: "What is the opposite gender for 'roe'?",
        optionA: 'buck',
        optionB: 'drake',
        optionC: 'drone',
        optionD: 'hart',
        correctAnswer: 'D',
        explanation: "'Roe' (female deer) pairs with the masculine 'hart'.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 17,
      },

      {
        questionSetId,
        slug: 'gender-masculine-mare',
        questionText: "What is the masculine gender of 'mare'?",
        optionA: 'mermaid',
        optionB: 'bear',
        optionC: 'stallion',
        optionD: 'dog',
        correctAnswer: 'C',
        explanation: "'Mare' is the feminine of 'stallion'.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 18,
      },

      {
        questionSetId,
        slug: 'gender-common-gender-deer',
        questionText: 'Which one is common gender?',
        optionA: 'deer',
        optionB: 'tiger',
        optionC: 'bull',
        optionD: 'dog',
        correctAnswer: 'A',
        explanation:
          "'Deer' can refer to either a male or female animal, making it a common gender noun; the other options are strictly masculine.",
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 19,
      },

      {
        questionSetId,
        slug: 'gender-neuter-computer',
        questionText: "My computer is out of order. Here 'computer' is —",
        optionA: 'masculine gender',
        optionB: 'feminine gender',
        optionC: 'neuter gender',
        optionD: 'common gender',
        correctAnswer: 'C',
        explanation:
          'Lifeless objects that are neither male nor female belong to the neuter gender.',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Gender',
        sortOrder: 20,
      },
    ],
    skipDuplicates: true,
  });

  console.log('✓ Gender (Lecture 09) seed inserted successfully');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
